# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: alorent- <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/06 20:56:27 by alorent-          #+#    #+#              #
#    Updated: 2018/10/06 21:06:57 by alorent-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = eval_expr

SRC = ft.c ft2.c ft3.c main.c opers.c

all:
	@gcc -Wall -Wextra -Werror $(SRC) -o $(NAME)

clean:
	@rm -f $(NAME)

fclean: clean

re: clean all
