# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: alorent- <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/07 11:50:10 by alorent-          #+#    #+#              #
#    Updated: 2018/10/07 19:01:14 by alorent-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = colle-

SRC = main.c rush

SRC2 = rushs00.c colle02.c ft.c ft2.c

all:
	@gcc -Wall -Wextra -Werror $(SRC)00.c -o $(NAME)00
	@gcc -Wall -Wextra -Werror $(SRC)01.c -o $(NAME)01
	@gcc -Wall -Wextra -Werror $(SRC)02.c -o $(NAME)02
	@gcc -Wall -Wextra -Werror $(SRC)03.c -o $(NAME)03
	@gcc -Wall -Wextra -Werror $(SRC)04.c -o $(NAME)04
	@gcc -Wall -Wextra -Werror $(SRC2) -o colle-2

fclean:
	@rm -f $(NAME)0* colle-2
